# most things are kept in separate config files. i like to keep this file as sparse as possible.
default_config:

tts:
  - platform: google_translate

# we're ignoring a lot of devices in zwave, so moved this out of the main config file.
zwave: !include zwave.yaml
zha:
  usb_path: /dev/ttyUSB1

homeassistant:
  # devices that require a lot of configuration are in packages just for easier readability.
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:
  themes: !include_dir_named theme
 
zone: !include zone.yaml

script: !include_dir_merge_named script
automation: !include_dir_merge_list automation
switch: !include_dir_list switch
light: !include_dir_merge_list light
group: !include_dir_named group
scene: !include_dir_merge_list scene
input_boolean: !include input_boolean.yaml

discovery:

# smart life/tuya devices.
tuya:
  username: !secret tuya_username 
  password: !secret tuya_password 
  country_code: US

# using dark sky for weather
weather:
  - platform: darksky
    api_key: !secret darksky_apikey 
    mode: daily

# google calendar
google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret 

# turn off lights when house is empty - requires sun 
device_sun_light_trigger:
sun:

ifttt:
  key: !secret ifttt_key

# by default, recorder saves to an sqlite file on disk
# if you've got a decent number of devices, this lags out
# rpi hard. moved to a mysql db on a different rpi.
# changing recorder to send to usb disk instead
recorder: !include recorder.yaml

# edit lovelace in yaml mode
lovelace:
  mode: yaml
