#
# in_bed is set by my withings sleep sensor and ifttt.
#
# todo: add conditions for
#  - if laptop is pingable at the end of those 5 minutes
#  - if media is playing on the bedroom apple tv
- alias: bedtime
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_off
      entity_id: group.every_light
    - service: switch.turn_off
      entity_id: group.desk_power_strip