# this is still a test automation. i also want this button
# to trigger a switch on the tuya platform to turn on my
# helping hand light, but tuya is being unreliable. will
# probably switch to ifttt instead of the tuya api before
# i can do this. i just wanted to pop this code into the
# repo as a reminder of how using zha_event with button
# presses works.

# for now, all of these buttons actions do the same thing:
# toggle the workbench lamp. but i want hold to toggle
# the helping hands light instead, and double tap will
# toggle both lamps.

- alias: Workbench Button Push
  trigger:
  - event_data:
      command: button_single
      device_ieee: "28:6d:97:00:01:03:8b:73"
    event_type: zha_event
    platform: event
  action:
    - service: light.toggle
      data:
        entity_id: light.workbench_lamp
        brightness_pct: 100
      

- alias: Workbench Button Hold
  trigger:
  - event_data:
      command: button_hold
      device_ieee: "28:6d:97:00:01:03:8b:73"
    event_type: zha_event
    platform: event
  action:
    - service: light.toggle
      data:
        entity_id: light.workbench_lamp
        brightness_pct: 100


- alias: Workbench Button Double
  trigger:
  - event_data:
      command: button_double
      device_ieee: "28:6d:97:00:01:03:8b:73"
    event_type: zha_event
    platform: event
  action:
    - service: light.toggle
      data:
        entity_id: light.workbench_lamp
        brightness_pct: 100