# package file for aeotec wallmote quad

# temporary actions for wallmote quad
# just a test to verify that it works
automation:
  - alias: Wallmote Button 1 Press
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 1
        scene_data: 0
    action:
    - service: script.morning_lights_transition

  - alias: Wallmote Button 1 Held
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 1
        scene_data: 2
    action:
    - service: script.morning_lights

  - alias: Wallmote Button 2 Press
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 2
        scene_data: 0
    action:
    - service: script.daytime_lights

  - alias: Wallmote Button 2 Held
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 2
        scene_data: 2
    action:
    - service: script.bright_lights

  - alias: Wallmote Button 3 Press
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 3
        scene_data: 0
    action:
    - service: script.evening_lights

  - alias: Wallmote Button 3 Held
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 3
        scene_data: 2
    action:
    - service: script.evening_dimmed_lights

  - alias: Wallmote Button 4 Press
    hide_entity: true
    trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_wallmote_quad
        scene_id: 4
        scene_data: 0
    action:
    - service: script.osu_lights

homeassistant:
  customize:
    # hidden devices
    sensor.bedroom_wallmote_quad_alarm_level:
      friendly_name: Bedroom Wallmote Quad Alarm Level
      hidden: true
    sensor.bedroom_wallmote_quad_alarm_type:
      friendly_name: Bedroom Wallmote Quad Alarm Type
      hidden: true
    switch.bedroom_wallmote_quad:
      friendly_name: Bedroom Wallmote Quad
      hidden: true
    zwave.bedroom_wallmote_quad:
      friendly_name: Bedroom Wallmote Quad
      hidden: true
    switch.bedroom_wallmote_quad_1:
      friendly_name: Bedroom Wallmote Quad Switch 1
      hidden: true
    switch.bedroom_wallmote_quad_1:
      friendly_name: Bedroom Wallmote Quad Switch 2
      hidden: true
    switch.bedroom_wallmote_quad_1:
      friendly_name: Bedroom Wallmote Quad Switch 3
      hidden: true
    switch.bedroom_wallmote_quad_1:
      friendly_name: Bedroom Wallmote Quad Switch 4
      hidden: true