# package files make multisensors easier to manage.

binary_sensor:
  - platform: template
    sensors:
      # create motion sensor from value of burglar node
      dining_room_motion:
        value_template: "{{ is_state('sensor.dining_room_multisensor_burglar', '8') }}"
      # create tamper sensor from value of burglar node
      dining_room_multisensor_tamper:
        value_template: "{{ is_state('sensor.dining_room_multisensor_burglar', '3') }}"

sensor:
  - platform: template
    sensors:
    # create battery sensor from zwave attributes
      dining_room_multisensor_battery:
        value_template: >-
          {% if states.zwave.dining_room_multisensor %}
            {{ states.zwave.dining_room_multisensor.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% set battery_level = states('sensor.dining_room_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    # hidden devices
    zwave.dining_room_multisensor:
      friendly_name: Dining Room Multisensor
      hidden: true
    binary_sensor.dining_room_multisensor:
      friendly_name: Dining Room Multisensor Sensor
      hidden: true
    sensor.dining_room_multisensor_alarm_level:
      friendly_name: Dining Room Multisensor Alarm Level
      hidden: true
    sensor.dining_room_multisensor_alarm_type:
      friendly_name: Dining Room Multisensor Alarm Type
      hidden: true
    sensor.dining_room_multisensor_burglar:
      friendly_name: Dining Room Multisensor Burglar
      hidden: true    
    sensor.dining_room_multisensor_system:
      friendly_name: Dining Room Multisensor System
      hidden: true

    # motion
    binary_sensor.dining_room_motion:
      friendly_name: Dining Room Motion
      device_class: motion
    
    # tamper
    binary_sensor.dining_room_multisensor_tamper:
      friendly_name: Dining Room Multisensor Tamper
      device_class: safety

    # battery
    sensor.dining_room_multisensor_battery:
      friendly_name: Dining Room Multisensor Battery
      device_class: battery
      unit_of_measurement: '%'

    # humidity
    sensor.dining_room_humidity:
      friendly_name: Dining Room Humidity 
      device_class: humidity
      icon: mdi:water-percent

    # luminance
    sensor.dining_room_luminance:
      friendly_name: Dining Room Luminance 
      device_class: illuminance 
      icon: mdi:brightness-5

    # temperature
    sensor.dining_room_temperature:
      friendly_name: Dining Room Temperature
      device_class: temperature
      unit_of_measurement: '°F'
