# package files make multisensors easier to manage.

binary_sensor:
  - platform: template
    sensors:
      # create motion sensor from value of burglar node
      hallway_motion:
        value_template: "{{ is_state('sensor.hallway_multisensor_burglar', '8') }}"
      # create tamper sensor from value of burglar node
      hallway_multisensor_tamper:
        value_template: "{{ is_state('sensor.hallway_multisensor_burglar', '3') }}"

sensor:
  - platform: template
    sensors:
      # create battery sensor from zwave attributes
      hallway_multisensor_battery:
        value_template: >-
          {% if states.zwave.hallway_multisensor %}
            {{ states.zwave.hallway_multisensor.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% set battery_level = states('sensor.hallway_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    # hidden devices
    zwave.hallway_multisensor:
      friendly_name: Hallway Multisensor
      hidden: true
    binary_sensor.hallway_multisensor:
      friendly_name: Hallway Multisensor Sensor
      hidden: true
    sensor.hallway_multisensor_alarm_level:
      friendly_name: Hallway Multisensor Alarm Level
      hidden: true
    sensor.hallway_multisensor_alarm_type:
      friendly_name: Hallway Multisensor Alarm Type
      hidden: true
    sensor.hallway_multisensor_burglar:
      friendly_name: Hallway Multisensor Burglar
      hidden: true
    sensor.hallway_multisensor_system:
      friendly_name: Hallway Multisensor System
      hidden: true

    # motion
    binary_sensor.hallway_motion:
      friendly_name: Hallway Motion
      device_class: motion

    # tamper
    binary_sensor.hallway_multisensor_tamper:
      friendly_name: Hallway Multisensor Tamper
      device_class: safety

    # battery
    sensor.hallway_multisensor_battery:
      friendly_name: Hallway Multisensor Battery
      device_class: battery
      unit_of_measurement: '%'

    # humidity
    sensor.hallway_humidity:
      friendly_name: Hallway Humidity 
      device_class: humidity
      icon: mdi:water-percent

    # luminance
    sensor.hallway_luminance:
      friendly_name: Hallway Luminance 
      device_class: illuminance
      icon: mdi:brightness-5

    # temperature
    sensor.hallway_temperature:
      friendly_name: Hallway Temperature
      device_class: temperature
      unit_of_measurement: '°F'
