# package files make multisensors easier to manage.

binary_sensor:
  - platform: template
    sensors:
      # create motion sensor from value of burglar node
      kitchen_motion:
        value_template: "{{ is_state('sensor.kitchen_multisensor_burglar', '8') }}"
      # create tamper sensor from value of burglar node
      kitchen_multisensor_tamper:
        value_template: "{{ is_state('sensor.kitchen_multisensor_burglar', '3') }}"

sensor:
  - platform: template
    sensors:
      # create battery sensor from zwave attributes
      kitchen_multisensor_battery:
        value_template: >-
          {% if states.zwave.kitchen_multisensor %}
            {{ states.zwave.kitchen_multisensor.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% set battery_level = states('sensor.kitchen_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    # hidden devices
    zwave.kitchen_multisensor:
      friendly_name: Kitchen Multisensor
      hidden: true
    binary_sensor.kitchen_multisensor:
      friendly_name: Kitchen Multisensor Sensor
      hidden: true
    sensor.kitchen_multisensor_alarm_level:
      friendly_name: Kitchen Multisensor Alarm Level
      hidden: true
    sensor.kitchen_multisensor_alarm_type:
      friendly_name: Kitchen Multisensor Alarm Type
      hidden: true
    sensor.kitchen_multisensor_burglar:
      friendly_name: Kitchen Multisensor Burglar
      hidden: true
    sensor.kitchen_multisensor_emergency:
      friendly_name: Kitchen Multisensor Emergency
      hidden: true
    sensor.kitchen_multisensor_system:
      friendly_name: Kitchen Multisensor System
      hidden: true

    # motion
    binary_sensor.kitchen_motion:
      friendly_name: Kitchen Motion
      device_class: motion

    # tamper
    binary_sensor.kitchen_multisensor_tamper:
      friendly_name: Kitchen Multisensor Tamper
      device_class: safety

    # battery
    sensor.kitchen_multisensor_battery:
      friendly_name: Kitchen Multisensor Battery
      device_class: battery
      unit_of_measurement: '%'

    # humidity
    sensor.kitchen_humidity:
      friendly_name: Kitchen Humidity 
      device_class: humidity
      icon: mdi:water-percent

    # luminance
    sensor.kitchen_luminance:
      friendly_name: Kitchen Luminance 
      device_class: illuminance
      icon: mdi:brightness-5

    # temperature
    sensor.kitchen_temperature:
      friendly_name: Kitchen Temperature
      device_class: temperature
      unit_of_measurement: '°F'
