# package files make multisensors easier to manage.

# cumulative motion sensor
binary_sensor:
  - platform: template
    sensors:
      living_room_motion:
        value_template: >-
          {{ is_state('binary_sensor.living_room_west_motion', 'on')
             or is_state('binary_sensor.living_room_east_motion', 'on')
             or is_state('binary_sensor.workbench_motion', 'on')
             or is_state('binary_sensor.desk_motion', 'on')}}

# create averages for temperateure, humidity, luminance
sensor:
  - platform: min_max
    type: mean
    name: living_room_temperature
    entity_ids:
      - sensor.living_room_east_temperature
      - sensor.living_room_west_temperature
      - sensor.desk_temperature
      - sensor.workbench_temperature
  - platform: min_max
    type: mean
    name: living_room_relative_humidity
    entity_ids:
      - sensor.living_room_east_humidity
      - sensor.living_room_west_humidity
      - sensor.workbench_humidity
  - platform: min_max
    type: mean
    name: living_room_luminance
    entity_ids:
      - sensor.living_room_east_luminance
      - sensor.living_room_west_luminance

homeassistant:
  customize:
    # motion
    binary_sensor.living_room_motion:
      friendly_name: Living Room Motion
      device_class: motion

    # humidity
    sensor.living_room_humidity:
      friendly_name: Living Room Humidity
      device_class: hummidity
      icon: mdi:water-percent

    # luminance
    sensor.living_room_luminance:
      friendly_name: Living Room Luminance
      device_class: illuminance
      icon: mdi:brightness-5

    # temperature
    sensor.living_room_temperature:
      friendly_name: Living Room Temperature
      device_class: temperature
      unit_of_measurement: '°F'
