# package files make multisensors easier to manage.

binary_sensor:
  - platform: template
    sensors:
      # create motion sensor from value of burglar node
      living_room_west_motion:
        value_template: "{{ is_state('sensor.living_room_west_multisensor_burglar', '8') }}"
      # create tamper sensor from value of burglar node
      living_room_west_multisensor_tamper:
        value_template: "{{ is_state('sensor.living_room_west_multisensor_burglar', '3') }}"

sensor:
  - platform: template
    sensors:
      # create battery sensor from zwave attributes
      living_room_west_multisensor_battery:
        value_template: >-
          {% if states.zwave.living_room_west_multisensor %}
            {{ states.zwave.living_room_west_multisensor.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% set battery_level = states('sensor.living_room_west_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    # hidden devices
    zwave.living_room_west_multisensor:
      friendly_name: Living Room West Multisensor
      hidden: true
    binary_sensor.living_room_west_multisensor:
      friendly_name: Living ROom West Multisensor Sensor
      hidden: true
    sensor.living_room_west_multisensor_alarm_level:
      friendly_name: Living Room West Multisensor Alarm Level
      hidden: true
    sensor.living_room_west_multisensor_alarm_type:
      friendly_name: Living Room West Multisensor Alarm Type
      hidden: true
    sensor.living_room_west_multisensor_appliance:
      friendly_name: Living Room West Multisensor Appliance
      hidden: true
    sensor.living_room_west_multisensor_burglar:
      friendly_name: Living Room West Multisensor Burglar
      hidden: true
    sensor.living_room_west_multisensor_clock:
      friendly_name: Living Room West Multisensor Clock
      hidden: true
    sensor.living_room_west_multisensor_emergency:
      friendly_name: Living Room West Multisensor Emergency
      hidden: true

    # motion
    binary_sensor.living_room_west_motion:
      friendly_name: Living Room West Motion
      device_class: motion

    # tamper
    binary_sensor.living_room_west_multisensor_tamper:
      friendly_name: Living Room West Multisensor Tamper
      device_class: safety

    # battery
    sensor.living_room_west_multisensor_battery:
      friendly_name: Living Room West Multisensor Battery
      device_class: battery
      unit_of_measurement: '%'
  
    # humidity
    sensor.living_room_west_humidity:
      friendly_name: Living Room West Humidity 
      device_class: humidity
      icon: mdi:water-percent

    # luminance
    sensor.living_room_west_luminance:
      friendly_name: Living Room West Luminance 
      device_class: illuminance
      icon: mdi:brightness-5
    
    # temperature
    sensor.living_room_west_temperature:
      friendly_name: Living Room West Temperature
      device_class: temperature
      unit_of_measurement: '°F'
