# package files make multisensors easier to manage.

binary_sensor:
  - platform: template
    sensors:
      # create motion sensor from value of burglar node
      workbench_motion:
        value_template: "{{ is_state('sensor.workbench_multisensor_burglar', '8') }}"
      # create tamper sensor from value of burglar node
      workbench_multisensor_tamper:
        value_template: "{{ is_state('sensor.workbench_multisensor_burglar', '3') }}"

sensor:
  - platform: template
    sensors:
      # create battery sensor from zwave attributes
      workbench_multisensor_battery:
        value_template: >-
          {% if states.zwave.workbench_multisensor %}
            {{ states.zwave.workbench_multisensor.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% set battery_level = states('sensor.workbench_multisensor_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
      # sometimes this sensor returns in C, other times it returns in F.
      # use a template to do basic sanity checking on the reported temp/convert to F.
      workbench_temperature:
        value_template: >-
          {% if states('sensor.workbench_multisensor_temperature') | int < 45 %}
            {{ states('sensor.workbench_multisensor_temperature') | float * 9 / 5 + 32  }}
          {% else %}
            {{ states('sensor.workbench_multisensor_temperature') }}
          {% endif %}

homeassistant:
  customize:
    # hidden devices
    zwave.workbench_multisensor:
      friendly_name: Workbench Multisensor
      hidden: true
    binary_sensor.workbench_multisensor:
      friendly_name: Workbench Multisensor Sensor
      hidden: true
    sensor.workbench_multisensor_alarm_level:
      friendly_name: Workbench Multisensor Alarm Level
      hidden: true
    sensor.workbench_multisensor_alarm_type:
      friendly_name: Workbench Multisensor Alarm Type
      hidden: true
    sensor.workbench_multisensor_burglar:
      friendly_name: Workbench Multisensor Burglar
      hidden: true
    sensor.workbench_multisensor_temperature:
      friendly_name: Workdesk Multisensor Temperature
      device_class: temperature
      hidden: true
  
    # motion
    binary_sensor.workbench_motion:
      friendly_name: Workbench Motion
      device_class: motion

    # tamper
    binary_sensor.workbench_multisensor_tamper:
      friendly_name: Workbench Multisensor Tamper
      device_class: safety

    # battery
    sensor.workbench_multisensor_battery:
      friendly_name: Workbench Multisensor Battery
      device_class: battery
      unit_of_measurement: '%'
    
    # humidity
    sensor.workbench_humidity:
      friendly_name: Workbench Humidity 
      device_class: humidity
      icon: mdi:water-percent

    # luminance
    sensor.workbench_luminance:
      friendly_name: Workbench Luminance 
      device_class: illuminance
      icon: mdi:brightness-5
      unit_of_measurement: "LUX"

    # temperature
    sensor.workbench_temperature:
      friendly_name: Workbench Temperature
      device_class: temperature
      unit_of_measurement: '°F'

    # ultraviolet
    sensor.workbench_ultraviolet:
      friendly_name: Workbench Ultraviolet
      icon: mdi:weather-sunny
      unit_of_measurement: "UV Index"
