title: Automations
badges: []
cards:
  - type: 'custom:monster-card'
    show_empty: false
    card:
      title: Automations
      type: entities
    filter:
      include:
        - domain: automation
      exclude:
        - entity_id: 'automation.wallmote*'
        - entity_id: 'automation.workbench_button*'
  - type: 'custom:monster-card'
    show_empty: false
    card:
      title: Scripts
      type: entities
    filter:
      include:
        - domain: script
  - type: 'custom:monster-card'
    show_empty: false
    card:
      title: Scenes
      type: entities
    filter:
      include:
        - domain: scene
      